projects:
  - name: jdk8-web
    harbor_repo: hub.dream22.xyz
    chart: jdk8-web
    environments:
      - name: dev
        cluster: dev-cluster
        namespaces:
          - coolgame-dev
      - name: prod
        cluster: prod-cluster
        namespaces:
          - coolgame-prod

harbor_auth:
  username: "admin"
  password: "YCb7WdB9dafp3UgX"

clusters:
  - name: dev-cluster
    helm_api: http://helm-api.dev.coolgame.io

  - name: prod-cluster
    helm_api: http://helm-api.prod.coolgame.io